### ISSUE TITLE
Format issue w parser pys

### ISSUE THREAD

**Issue by marisalim** [marisalim/Saiga#3]
System: Ubuntu

**File Pipeline_scripts/clstr_parser.py - line 64 (for loop)**

`for j in range(0, myiso.count('>')):`

should be replaced by: `for j in range(0, int(myiso.count('>')/2)):`

There are 2 '>' signs for each cluster (|>Consensus and >clstr)
(e.g. "509nt,>clstr0|>Consensus...*1504nt,>clstr1|>Consensus...at-/95.24%")

- line 65:
`clstrID = myiso.split('|Consensus...')[j].split('>clstr')[1]`
should be replaced by:
`clstrID = myiso.split('|>Consensus...')[j].split('>clstr')[1]`

**************************************************
** Same comments for Pipeline_scripts/statparser.py **

**Comment by ordynets** [comment]
Dear @marisalim, 
your troubleshooting solution was indeed helpful to fix the work of cdhit and medaka. 

However, now I get the error message two steps forward in the pipeline. It points exactly to the changed line of 'stat_parser.py'.
I copy the output from the terminal.
I will be grateful for a hint.

Kind regards
Alexander


`######################################################################
######################################################################
Parse outputs, calculate ID stats.
######################################################################
Make blast db header file if does not exist
-------------------------------------------------------------
Running script: /mnt/c/Users/aordy/OneDrive/Documents/Projects/Nanopore/2_explorative/test_saiga_20220201_v2/Pipeline_scripts/stat_parser.py
-------------------------------------------------------------
Parsing data...
  File "/mnt/c/Users/aordy/OneDrive/Documents/Projects/Nanopore/2_explorative/test_saiga_20220201_v2/Pipeline_scripts/stat_parser.py", line 103
    clstrID = myiso.split('|>Consensus...')[j].split('>clstr')[1] myiso.count  
                                                                  ^
SyntaxError: invalid syntax`

**Comment by marisalim** [comment]
Hi Alexander - thanks for writing!

Would you mind sharing the lines of code that you edited in the parser script? The invalid syntax error looks like it's pointing to the space between the `myiso.split()` command and `myiso.count`. Are you trying to print out the contents of `myiso.count`?

**Comment by ordynets** [comment]
Dear Marisa,
Thank you for the prompt response! 
Indeed ` myiso.count` has nothing to do with that line. It was my copy/past mistake. The parsing works fine when this line in 'stat_parser.py' is as you designed. i.e.:
```
clstrID = myiso.split('|>Consensus...')[j].split('>clstr')[1]
```
Apparently, it is due to your troubleshooting solution (15 June 2020) that the style of the `query` in your `SAIGA_demo_results.txt` and my demo run `_parsedout.txt` differ. I mean, for example for sample `FFPEduck01qiagen`, your version `clstr0|Consensus:1.0-453.0` versus mine `clstr0|>Consensus`. I notice also the loss of this numeric ending of the string in my case. I observe it after Medaka's action. That is, I see the values like yours in the medaka log output but in the `consensus.fasta` where Medaka writes in the polished consensus, the version like mine. It is a bit less informative but not dramatic, right?
In [medaka GitHub issues](https://github.com/nanoporetech/medaka/issues/269#issuecomment-793957244) I read
>fasta headers are simply the input contig names *possibly* decorated with coordinates tracing to which part of the input sequence the output sequence corresponds

**Comment by marisalim** [comment]
Yes, that looks like the issue, thanks for documenting it! The Medaka output header format has changed slightly since I wrote the parser script (thus the differences from the demo data). For that line of the script, the goal is to extract the cluster number information, so the part that comes after "Consensus" shouldn't be needed and it's possible that just a few tweaks are needed to edit the parsing scripts. Alternatively, you can check out [NGSpeciesID](https://github.com/ksahlin/NGSpeciesID) for the clustering steps which should be up-to-date with Medaka, and parse the outputs separately after the analysis.
